const target = document.querySelector('#data-freshness');
const jakarta = new Intl.DateTimeFormat('en-GB', { timeZone: 'Asia/Jakarta', dateStyle: 'medium', timeStyle: 'medium' });
const style = document.createElement('style');
style.textContent = `#data-freshness{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;max-width:1180px;margin:0 auto 18px;padding:0 18px;color:var(--ink,#f2f0ea);font:12px/1.4 Manrope,ui-sans-serif,system-ui,sans-serif}.freshness-card{min-width:0;padding:12px 14px;border:1px solid var(--line,#252a27);border-radius:10px;background:var(--surface,#131615)}.freshness-card[data-state=stale]{border-color:var(--amber,#d9b46a)}.freshness-card[data-state=error]{border-color:var(--red,#eb8e88)}.freshness-title{display:flex;justify-content:space-between;gap:12px;font-weight:700}.freshness-state{color:var(--green,#b8d884);white-space:nowrap}[data-state=stale] .freshness-state{color:var(--amber,#d9b46a)}[data-state=error] .freshness-state{color:var(--red,#eb8e88)}.freshness-detail{display:grid;gap:3px;margin-top:7px;color:var(--muted,#8d918d)}.freshness-detail strong{color:var(--ink,#f2f0ea);font-weight:500}@media(max-width:680px){#data-freshness{grid-template-columns:1fr;padding:0 12px}}`;
document.head.append(style);
function age(ms){if(ms==null||!Number.isFinite(Number(ms)))return'Unavailable';const seconds=Math.max(0,Math.round(Number(ms)/1000));if(seconds<60)return`${seconds}s ago`;const minutes=Math.round(seconds/60);if(minutes<60)return`${minutes}m ago`;return`${Math.floor(minutes/60)}h ${minutes%60}m ago`}
function timestamp(ms){return ms==null?'Unavailable':`${jakarta.format(new Date(Number(ms)))} WIB`}
function card(title,freshness){const state=freshness?.stale?'stale':freshness?.freshness_ms==null?'error':'current';const label=state==='stale'?'STALE':state==='current'?'CURRENT':'UNAVAILABLE';return`<article class="freshness-card" data-state="${state}"><div class="freshness-title"><span>${title}</span><span class="freshness-state">${label}</span></div><div class="freshness-detail"><span>Age: <strong>${age(freshness?.freshness_ms)}</strong></span><span>Source timestamp: <strong>${timestamp(freshness?.updated_at_ms)}</strong></span><span>Source: <strong>${freshness?.source??'Unavailable'}</strong></span></div></article>`}
async function refresh(){try{const response=await fetch('/api/intelligence',{cache:'no-store'});if(!response.ok)throw new Error(`HTTP ${response.status}`);const data=await response.json();target.innerHTML=`${card('Historical intelligence',data.freshness)}${card('Order book',data.order_book_freshness)}`}catch(_error){target.innerHTML='<article class="freshness-card" data-state="error"><div class="freshness-title"><span>Data freshness</span><span class="freshness-state">UNAVAILABLE</span></div><div class="freshness-detail"><span>Unable to read freshness metadata.</span></div></article>'}}
refresh();setInterval(refresh,5000);
